## setup

In [1]:
import numpy as np
from importlib import reload
from scipy.stats import poisson, geom, expon
import pandas as pd
from src.util import saveobj, loadobj
from src import influence_discrete

In [2]:
# plotting requirements
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
#Large graphs by default
mpl.rcParams['figure.figsize'] = (10.0, 8.0)

In [3]:
from sklearn.linear_model import LassoCV, LassoLarsCV, LassoLarsIC
from sklearn import datasets

diabetes = datasets.load_diabetes()
X = diabetes.data
y = diabetes.target


In [4]:
lm = LassoLarsIC()
lm.fit(X,y)
lm.coef_

array([   0.        , -197.75650114,  522.26484702,  297.15973689,
       -103.94624877,    0.        , -223.92603334,    0.        ,
        514.74948085,   54.76768063])

In [11]:
from src import weighted_linear_model
weighted_linear_model = reload(weighted_linear_model)

wlm = weighted_linear_model.WeightedLassoLarsIC()
wlm.fit(X,y)
wlm.coef_

array([[   0.        , -197.75650114,  522.26484702,  297.15973689,
        -103.94624877,    0.        , -223.92603334,    0.        ,
         514.74948085,   54.76768063]])

In [12]:
from src import weighted_linear_model
weighted_linear_model = reload(weighted_linear_model)

sw = np.ones(X.shape[0])
sw[200:] = 0

wlm = weighted_linear_model.WeightedLassoLarsIC()
wlm.fit(X,y, sample_weight=sw)
wlm.coef_

array([[-219.80909215, -235.39955675,  574.57728491,  180.53137819,
        -355.05988881,    0.        , -118.2812037 ,    0.        ,
         583.5454464 ,   95.99412312]])

In [13]:
from src import weighted_linear_model
weighted_linear_model = reload(weighted_linear_model)

wlm = weighted_linear_model.WeightedLassoLarsIC()
wlm.fit(X,y, penalty_weight='adaptive')
wlm.coef_

array([[   0.        , -197.75650114,  522.26484702,  297.15973689,
        -103.94624877,    0.        , -223.92603334,    0.        ,
         514.74948085,   54.76768063]])

In [ ]:
import pdb; pdb.pm()

In [10]:
wlm.penalty_weight

array([[ 0.76490672,  0.00482638,  0.0020421 ,  0.00331379,  0.01198092,
         0.01411869,  0.00529997,  0.00864209,  0.0022532 ,  0.01152757]])

In [18]:
np.cumsum([5,6,7])dd

array([ 5, 11, 18])